import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,

} from 'react-icons/ai';
import deved from '../public/giphy.webp';
import react from '../public/React-icon.svg.png';
import nodejs from '../public/node-icon.png';
import mongodb from '../public/mongodb-icon.png';
import prj1 from '../public/mobile-point.webp';
import prj2 from '../public/easy-learning.webp';
import prj3 from '../public/mental-health.webp';
import { useState } from 'react';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

//   {
//     localStorage.setItem('theme', darkMode)
// }

  return (
    <div className={darkMode ? "dark":"light"}>
      <Head>
        <title>Yamin Arafat portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/*body section start */}

      <main style={{backgroundColor: darkMode ? 'rgb(17 24 39)':'',color: darkMode ? 'white':''}} className='px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons">developedbyya</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className="cursor-pointer"/>
            </li>
            <li>
              <a className="bg-gradient-to-t from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">resume</a>
            </li>
          </ul>
          </nav>
          <div className='md:flex'>
          <div>
          <div className='text-center p-10 py-10'>
            <h2 className="text-5xl py-2 text-teal-600 font-medium ">Yamin Arafat</h2>
            <h3 className="text-2xl py-2">Frontend Developer</h3>
            <p className='text-md py-5 leading-8 ' style={{color: darkMode ? 'white':'rgb(55 65 81)'}}>developing website with react & next. Join me down below and lets get cracking!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3' style={{color: darkMode ? 'white':'rgb(55 65 81)'}}>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          </div>
          <div className="relative mx-auto bg-gradient-to-b my-5 from-teal-500 rounded-full w-80 h-80 overflow-hidden">
            <Image src={deved} alt='yamin'  className=' rounded-full w-80 h-80' />
          </div>
          </div>
        </section>
        {/* section 2 */}
        <section>
          <div className="">
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 "  style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>
              Since the beginning of my jurney as a frontend developer & designer. 
              <span className="text-teal-500"> agencies </span>consulted for <span className="text-teal-500">startUp</span> and collaborated with talanted people to create digital for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>
              I offer from a wide range of services, including programming and teaching.
            </p>
          </div>
          <div className="">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt='' src={react} className="
              bg-gray-800 mx-auto" width={100} height={100} />
              <h3 className='text-lg font-medium'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your need design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className=" py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>PhotoShop</p>
              <p className="py-1"  style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>Illustrator</p>
              <p className="py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt='' src={nodejs} className="
              bg-gray-800 mx-auto" width={100} height={100} />
              <h3 className='text-lg font-medium'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your need design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className="py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>PhotoShop</p>
              <p className="py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>Illustrator</p>
              <p className="py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt='' src={mongodb} className="
              bg-gray-800 mx-auto" width={100} height={100} />
              <h3 className='text-lg font-medium'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your need design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className="py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>PhotoShop</p>
              <p className="py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>Illustrator</p>
              <p className="py-1" style={{color: darkMode ? 'white':'rgb(31 41 55)'}}>Figma</p>
            </div>
          </div>
        </section>
        {/* section 3 */}
        <section>
          <div className="">
            <h3 className="text-3xl py-1">portfolio</h3>
            <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            <div className="basis-1/3 flex-1">
              <Image src={prj1} alt='' className="rounded-lg mx-auto m-5 w-[300px] h-[300px]" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={prj2} alt='' className="rounded-lg  mx-auto m-5 w-[300px] h-[300px]" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={prj3} alt='' className="rounded-lg  mx-auto m-5 w-[300px] h-[300px]" />
            </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
